config/routes.rb
Rails.application.routes.draw do

  root 'owners#home'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  resources :users do
    resources :owners do
      resources :pets do
      end
    end
    resources :walkers
  end

end

app/models/owner.rb
class Owner < ActiveRecord::Base

  belongs_to :user

  has_many :pets

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :owner
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :password, confirmation: true
  validates :password_confirmation, presence: true
  validates :password, length: { minimum: 6 }

  validates :email, presence: true
  validates :email, uniqueness: true
  validates :email, confirmation: true
  validates :email_confirmation, presence: true

  has_many :owners
  has_many :walkers
end

app/models/walker.rb
class Walker < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user


  # def current_user
  #   @current_user ||=
  #   User.find(session[:user_id]) if session[:owner_id]
  # end

  def current_user
    @current_user ||=
    User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless
    current_user
  end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController


  def home
    @bg = "bg-1"
  end

  def index
    @bg = "bg-2"
    @user = User.find(session[:user_id]) if session[:user_id]
    @owner = Owner.find(params[:owner_id])
    @pets = @owner.pets
  end

  def new
    @bg = "bg-3"
    @owner = Owner.new
    @action = :create
  end

  def create
    owner = Owner.create(owner_params[:owner])
    redirect_to user_owner_path(params[:user_id], owner.id)
  end


  def edit
    @bg = "bg-4"
    id = params[:id]
    @owner = Owner.find(id)
    @action = :update
  end

  def show
    @user = User.find(params[:user_id])
    @owner = @user.owners[0]
    @pets = @owner.pets
  end

  def update
    Owner.update(params[:id], owner_params[:owner])
    redirect_to owner_path(params[:id])
  end

  def destroy
    Owner.destroy(params[:id])
    redirect_to owners_path
  end

  private

  def owner_params
    params.permit(owner:[:id, :first_name, :last_name, :user_id, :bio])
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def new
    @bg = "bg-6"
    @pet = Pet.new
    @action = :create
  end

  def create
    @pet = Pet.create(pet_params[:pet])
    redirect_to user_owner_path(params[:user_id], @pet.owner_id)
  end


  def edit
    @bg = "bg-7"
    id = params[:id]
    @pet = Pet.find(id)
    @action = :update
  end


  def update
    #need owner id and pet id.
    id = params[:id]
    pet = Pet.find(id)
    owner = pet.owner_id
    pet.update(
      name: pet_params[:pet][:name],
      bio: pet_params[:pet][:bio],
      walk_frequency: pet_params[:pet][:walk_frequency],
      image: pet_params[:pet][:image]
    )
    redirect_to user_owner_path(params[:user_id], owner)
  end


  def destroy
    id = params[:id]
    pet = Pet.find(id)
    owner_id = pet.owner_id
    Pet.destroy(params[:id])
    redirect_to user_owner_path(params[:user_id], owner_id)
  end

  private

  def pet_params
    params.permit(pet:[:name, :bio, :walk_frequency, :owner_id, :image, :user_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @bg = "bg-8"
  end

# creates a session for a dog Owner
# here is where we can create a session for a user, but then we can define
#whether or not that user is an owner or a walker
  def create
    @user = User.find_by_email(params[:session][:email])
      if @user && @user.authenticate(params[:session][:password])
        session[:user_id] = @user.id
        owner = Owner.where(:user_id == @user.id)
        redirect_to user_owner_path(@user, owner)
      else
        flash[:alert] = "Your username/password combination was invalid."
        redirect_to 'login'
      end
  end

# creates a session for a dog Walker
  # def create_walker
  #   @user = User.find_by_email(params[:session][:email])
  #     if @user && @user.authenticate(params[:session][:password])
  #       session[:user_id] = @user.id
  #       walker = Walker.where(:user_id == @user.id)
  #       redirect_to user_walker_path(@user, walker)
  #     else
  #       flash[:alert] = "Your username/password combination was invalid."
  #       redirect_to 'login'
  #     end

  # end

  def destroy
    session[:user_id] = nil
    redirect_to "/"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @bg = "bg-9"
    @user = User.new
    @action = :create
  end

  def index
    @bg = "bg-10"
  end

  def show
    @bg = "bg-11"
    id = params[:id]
    @user = User.find(id)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      redirect_to 'signup'
    end
  end


  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/walkers_controller.rb
class WalkersController < ApplicationController

  def new
    @bg = "bg-12"
    @walker = Walker.new
    @action = :create
  end

  def create
    walker = Walker.create(walker_params[:walker])
    redirect_to user_walker_path(params[:user_id], walker.id)
  end

  def show
    @bg = "bg-13"
    @walker = Walker.find(params[:id])
  end

  private

  def walker_params
    params.permit(walker:[:id, :first_name, :last_name, :user_id, :bio, :walker_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/walkers_helper.rb
module WalkersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='https://fonts.googleapis.com/css?family=Quattrocento+Sans|Antic' rel='stylesheet' type='text/css'>
  <title>DogWalker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/nav' %>

<div class="jumbotron jumbotron-custom <%= @bg %>">

<div class="container">

<%= yield %>

</div>
</div>

</body>
</html>

app/views/owners/edit.html.erb
<%= render 'shared/ownerform' %>

app/views/owners/home.html.erb
  <div class="title-fade col-xs-6">


    <h1 class="">Dogs of Seattle</h1>

    <h3>Welcome!</h3>

    <p>Dogs of Seattle is a free website to help connect dog owners with dog walkers.
      <br>
      <br>
      Try it today!</p>

      <%= link_to "Sign up here", 'signup', class:"btn btn-default" %>
      <br>
      <br>
    </div>
    <div class="col-xs-6"></div>

app/views/owners/index.html.erb
<h3>Welcome, <%= @owner.first_name %>!</h3>

<br>
<%= link_to "Add a Pet", new_user_owner_pet_path(params[:user_id], @owner.id), class:"btn btn-default" %>
<br>
<br>
  <% @pets.each do |pet| %>
    <%= pet.name %>
    <br>
    <% if !pet.image.nil? %>
      <%= image_tag pet.image.url(:medium) %>
      <br>
      <%= pet.bio %>
      <br>
      <br>
      <%= link_to "Edit", edit_user_owner_pet_path(params[:user_id], @owner.id, pet.id), class:"btn btn-default" %>
      <%= link_to "Remove", user_owner_pet_path(params[:user_id], @owner.id, pet.id), method: :delete, class:"btn btn-default" %>
      <br>
    <% end %>
  <% end %>

app/views/owners/new.html.erb
  <div class="col-md-2"></div>
  <div class="col-md-8">
  <%= form_for @owner, url:{ action: @action } do |f| %>
    <h3>Please complete the following information to create your profile</h3>
    <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class:"form-control" %>
    </div>
    <br>
    <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class:"form-control" %>
    </div>
    <br>
    <h4>Tell your future dog walker a bit about yourself and what you're looking for in a dog walker:</h4>
    <div class="form-group">
    <%= f.label :bio %>
    <%= f.text_area :bio, class:"form-control" %>
    </div>
    <br>
    <%= f.hidden_field :user_id, value: params[:user_id] %>
    <br>
    <%= f.submit "Submit", :class => 'btn btn-default' %>
  <% end %>
  </div>
  <div class="col-md-2"></div>

app/views/owners/show.html.erb
<div class="row">

  <div class="title-fade col-xs-6">
    <h3>Welcome, <%= @owner.first_name %>!</h3>
    <p>In a future version of this, there will be a carousel will display the
      last 5 five dog walkers that have created an account with a picture. It
      will also have a link to the user's profile, where the user can edit their
      information. FANCY!</p>
    <br>
    <%= link_to "Add a Pet", new_user_owner_pet_path(params[:user_id], @owner.id), class:"btn btn-default" %>
    <br>
    <br>
  </div>
</div>

<div class="row">
<% if !@pets.nil? %>
  <% @pets.each do |pet| %>
    <h3><%= pet.name %></h3>
    <br>
    <% if !pet.image_file_name.nil? %>
      <%= image_tag pet.image.url(:medium) %>
    <% else %>
      <%= image_tag("default-dog", alt: "Default image for dog") %>
    <% end %>
    <br>
    <h4><%= pet.bio %></h4>
    <%= link_to "Edit", edit_user_owner_pet_path(params[:user_id], @owner.id, pet.id), class:"btn btn-default" %>
    <%= link_to "Remove", user_owner_pet_path(params[:user_id], @owner.id, pet.id), method: :delete, class:"btn btn-default" %>
    <br>
    <br>
  <% end %>
<% end %>
</div>

app/views/pets/edit.html.erb
<%= render 'shared/petform' %>

app/views/pets/new.html.erb
<%= render '/shared/petform' %>

app/views/shared/_nav.html.erb
<header>
    <%= link_to root_url do %>
    <div class="logo">
      <h6>D</h6>
    </div>
    <% end %>

    <nav>
      <% if current_user %>
        <%= link_to "Account", user_path(current_user), class: 'nav_font' %>
        <%= link_to "Log Out", logout_path, class: 'nav_font' %>
      <% else %>
        <%= link_to "Sign Up", signup_path, class: 'nav_font' %>
        <%= link_to "Log In", login_path, class: 'nav_font' %>
      <% end %>
    </nav>
  </header>

app/views/shared/_ownerform.html.erb
<div class="col-md-4"></div>
<div class="col-md-4">
<fieldset>
  <%= form_for @owner do |f| %>
    <h1>Profile page</h1>
    <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class:"form-control" %>
    </div>
    <br>
    <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class:"form-control" %>
    </div>
    <br>
    <div class="form-group">
    <%= f.label :bio %>
    <%= f.text_field :bio, class:"form-control" %>
    </div>
    <%= f.hidden_field :user_id, value: params[:user_id] %>
    <br>
    <%= f.submit "Submit", :class => 'submit_button btn btn-default' %>
  <% end %>
</div>
<div class="col-md-4"></div>

app/views/shared/_petform.html.erb
<div class="col-md-4"></div>
<div class="col-md-4 title-fade">
<%= form_for @pet, url:{ action: @action }, html: {multipart: true } do |f| %>
  <h3>Pet Profile</h3>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>
<br>
  <p> Write a brief bio for your dog to give dog walkers a sense of your pup</p>
  <div class="form-group">
  <%= f.label :bio %>
  <%= f.text_area :bio, class:"form-control" %><br>
  </div>
  <p>Tell us the frequency with which you'd like a walker to walk your dog</p>
  <div class="form-group">
  <%= f.label :walk_frequency %>
  <%= f.text_field :walk_frequency, class:"form-control" %><br>
  </div>
  <p> Upload your pug's mug!</p>
  <div class="form-group">
  <%= f.label :image %><br>
  <%= f.file_field :image %><br>
  </div>
  <%= f.hidden_field :owner_id, value: params[:owner_id] %><br>
  <%= f.submit "Submit", :class => 'submit_button btn btn-default' %>
<% end %>
<br>
</div>
<div class="col-md-4"></div>

app/views/users/index.html.erb
<h3>Here is where we wil define if they are a walker or an owner</h3>

app/views/users/new.html.erb
<div class="col-sm-4"></div>
<div class="col-sm-4 title-fade">
<fieldset>
  <%= form_for @user, url:{ action: @action } do |f| %>
    <h3>Sign up here!</h3>
    <br>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class:"form-control" %>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class:"form-control" %>
    </div>
    <br>
    <%= f.submit "Submit", :class => 'btn btn-default' %>
  <% end %>
  <p>

  </p>
</fieldset>
</div>
<div class="col-sm-4"></div>

app/views/users/show.html.erb
<div class="col-md-2"></div>
<div class="col-md-8 title-fade">
<h3>Get started by selecting one of the two options below</h3>
<br>

<%= link_to "I am an owner with a dog that needs more walks!", new_user_owner_path(@user.id), class: "btn btn-default" %>
<br>
<br>
<%= link_to "I am a person that wants to walk dogs!", new_user_walker_path(@user.id), class: "btn btn-default" %>
<p>
  <br>
</p>
</div>
<div class="col-md-2"></div>

app/views/walkers/new.html.erb
<div class="col-md-2"></div>
<div class="col-md-8">

<%= form_for @walker, url:{ action: @action } do |f| %>
  <h3>Please complete the following information to create your profile</h3>
  <div class="form-group">
  <%= f.label :first_name %>
  <%= f.text_field :first_name, class:"form-control" %>
  </div>
  <br>
  <div class="form-group">
  <%= f.label :last_name %>
  <%= f.text_field :last_name, class:"form-control" %>
  </div>
  <br>
  <h4>Tell your future dog owner a bit about yourself:</h4>
  <div class="form-group">
  <%= f.label :bio %>
  <%= f.text_area :bio, class:"form-control" %>
  </div>
  <br>
  <%= f.hidden_field :user_id, value: params[:user_id] %>
  <br>
  <%= f.submit "Submit", :class => 'btn btn-default' %>
<% end %>


</div>
<div class="col-md-2"></div>

app/views/walkers/show.html.erb
<div class="title-fade col-xs-6">
<h3>Welcome, <%= @walker.first_name %>!</h3>
<p>In a future version of this, there will be a carousel will display the <br>
  last 5 five dog owners that have created an account with a picture. It <br>
  will also have a link to the user's profile, where the user can edit their<br>
  information. There will also be the ability to message dog owners. FANCY!</p>
</div>